# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/b9607b09-b777-4ff7-53dc-287727eb8574/volume/combined_recipe, last modified Mon Sep 21 09:39:18 2020
# ------------------------------------------------

package:
    name: cffi
    version: 1.14.3
source:
    patches:
        - 0001-Link-to-dl-library.patch
        - setup-linux.patch
    sha256: f92f789e4f9241cd262ad7a555ca2c648a98178a953af117ef7fad46aa1d5591
    url: https://pypi.io/packages/source/c/cffi/cffi-1.14.3.tar.gz
build:
    number: '0'
    script: /opt/concourse/worker/volumes/live/b9607b09-b777-4ff7-53dc-287727eb8574/volume/cffi_1600699191154/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
        -m pip install . --no-deps -vv
    string: py38hed5b41f_0
requirements:
    build:
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libllvm10 10.0.0 h21ff451_2
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_2
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 h1de35cc_1
        - libffi 3.3 hb1e8313_2
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - pip 20.2.2 py38_0
        - pycparser 2.20 py_2
        - python 3.8.5 h26836e1_1
        - readline 8.0 h1de35cc_0
        - setuptools 49.6.0 py38_0
        - sqlite 3.33.0 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - libffi >=3.3,<3.4.0a0
        - pycparser
        - python >=3.8,<3.9.0a0
test:
    commands:
        - pip check
    imports:
        - _cffi_backend
        - cffi
    requires:
        - openssl
        - pip
about:
    description: 'Cffi aims to allow users to call C code from Python without having
        to

        learn a 3rd language. It provides a convenient and reliable way to call

        compiled C code from Python using interface declarations written in C.

        '
    dev_url: https://bitbucket.org/cffi/cffi/overview
    doc_source_url: https://bitbucket.org/cffi/cffi/src/default/doc/?at=default
    doc_url: http://cffi.readthedocs.org
    home: https://bitbucket.org/cffi/cffi
    license: MIT
    license_file: LICENSE
    summary: Foreign Function Interface for Python calling C code.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
        - inducer
        - mingwandroid
        - ocefpaf
