# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/87b0d714-aa88-46ba-53f8-e2f6e03e55a6/volume/combined_recipe, last modified Fri Sep 18 10:54:35 2020
# ------------------------------------------------

package:
    name: mkl_fft
    version: 1.2.0
source:
    sha256: ab34e4a3f3aaa983260b528ec8d7f2b98fcbfebd23c1462315e2efdb92395767
    url: https://github.com/IntelPython/mkl_fft/archive/v1.2.0.tar.gz
build:
    number: '0'
    script: /opt/concourse/worker/volumes/live/87b0d714-aa88-46ba-53f8-e2f6e03e55a6/volume/mkl_fft_1600444495847/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        setup.py build install --single-version-externally-managed --record=record.txt
    string: py38hc64f4ea_0
requirements:
    build:
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - clangxx_osx-64 10.0.0 h05bbb7f_1
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libllvm10 10.0.0 h21ff451_2
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_2
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - cython 0.29.21 py38hb1e8313_0
        - intel-openmp 2019.4 233
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 h1de35cc_1
        - libffi 3.3 hb1e8313_2
        - libgfortran 3.0.1 h93005f0_2
        - mkl 2019.4 233
        - mkl-devel 2019.4 233
        - mkl-include 2019.4 233
        - mkl-service 2.3.0 py38hfbe908c_0
        - ncurses 6.2 h0a44026_1
        - numpy-base 1.14.6 py38h6575580_4
        - numpy-devel 1.14.6 py38h4ba5984_4
        - openssl 1.1.1g h1de35cc_0
        - python 3.8.5 h26836e1_1
        - readline 8.0 h1de35cc_0
        - setuptools 49.6.0 py38_0
        - six 1.15.0 py_0
        - sqlite 3.33.0 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - blas 1.0 mkl
        - libcxx >=10.0.0
        - mkl >=2019.4,<2020.0a0
        - mkl-service >=2,<3.0a0
        - numpy >=1.14.6,<2.0a0
        - python >=3.8,<3.9.0a0
test:
    commands:
        - nosetests -v mkl_fft
    imports:
        - mkl_fft
        - mkl_fft._numpy_fft
        - mkl_fft._scipy_fft
    requires:
        - nose
about:
    description: NumPy-based implementation of Fast Fourier Transform using Intel
        (R) Math Kernel Library. Supports in-place and out-of-place, 1D and ND complex
        FFT on arrays of single and double precision with arbitrary memory layout,
        so long as array strides are multiples of its itemsize.
    home: http://github.com/IntelPython/mkl_fft
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: NumPy-based implementation of Fast Fourier Transform using Intel (R)
        Math Kernel Library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - oleksandr-pavlyk
