# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /Users/distiller/project/builder/conda/pytorch-nightly, last modified Fri Jul 24 22:22:41 2020
# ------------------------------------------------

package:
    name: pytorch
    version: 1.6.0
source:
    path: /Users/distiller/project/pytorch
build:
    detect_binary_files_with_prefix: false
    number: '0'
    script_env:
        - CMAKE_ARGS
        - CONDA_CUDATOOLKIT_CONSTRAINT
        - CUDA_VERSION
        - CUDNN_VERSION
        - DEBUG
        - DEVELOPER_DIR
        - EXTRA_CAFFE2_CMAKE_FLAGS
        - USE_CUDA
        - USE_DISTRIBUTED
        - USE_FBGEMM
    string: py3.8_0
requirements:
    build:
        - bzip2 1.0.8 h1de35cc_0
        - ca-certificates 2020.6.24 0
        - cmake 3.14.0 haff7e42_0
        - expat 2.2.9 hb1e8313_2
        - krb5 1.18.2 h75d18d8_0
        - libcurl 7.71.1 h8a08a2b_1
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 h1de35cc_1
        - libssh2 1.9.0 ha12b0ac_1
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - rhash 1.3.8 ha12b0ac_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    host:
        - blas 1.0 openblas
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py38_0
        - intel-openmp 2020.1 216
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 h1de35cc_1
        - libffi 3.3 hb1e8313_2
        - libgfortran 3.0.1 h93005f0_2
        - libiconv 1.16 h1de35cc_0
        - libopenblas 0.3.10 h0794777_0
        - libuv 1.26.0 h1de35cc_0
        - mkl 2020.1 216
        - mkl-include 2020.1 216
        - ncurses 6.2 h0a44026_1
        - ninja 1.9.0 py38h04f5b5a_0
        - numpy 1.11.3 py38h926163e_15
        - numpy-base 1.11.3 py38ha711998_15
        - openssl 1.1.1g h1de35cc_0
        - pip 20.1.1 py38_1
        - pkg-config 0.29.2 h3efe00b_8
        - python 3.8.3 h26836e1_2
        - pyyaml 5.3.1 py38haf1e3a3_1
        - readline 8.0 h1de35cc_0
        - setuptools 49.2.0 py38_0
        - sqlite 3.32.3 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - yaml 0.2.5 haf1e3a3_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - blas * mkl
        - mkl >=2018
        - ninja
        - numpy >=1.11
        - python >=3.8,<3.9.0a0
test:
    commands:
        - OMP_NUM_THREADS=4 python ./test/run_test.py || true
    imports:
        - torch
    source_files:
        - test
about:
    home: http://pytorch.org/
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: PyTorch is an optimized tensor library for deep learning using GPUs and
        CPUs.
extra:
    copy_test_source_files: true
    final: true
