# This file created by conda-build 3.20.4
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/154411f3-d48f-4a09-5dc8-199c488b22f9/volume/rsync-recipes/conda-4.9.0-python_3.8-on-osx, last modified Wed Oct 14 12:10:15 2020
# ------------------------------------------------

package:
    name: conda
    version: 4.9.0
source:
    fn: conda-4.9.0.tar.gz
    sha256: 18a9c31d797d5ff0f774fce18086c67ef369138b260a611334cd9b28d8dc9bba
    url: https://github.com/conda/conda/archive/4.9.0.tar.gz
build:
    always_include_files:
        - bin/activate
        - bin/conda
        - bin/deactivate
    number: '0'
    string: py38_0
requirements:
    host:
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 py38_0
        - conda-package-handling 1.6.1 py38h1de35cc_0
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 h1de35cc_1
        - libffi 3.3 hb1e8313_2
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1h haf1e3a3_0
        - pip 20.2.3 py38_0
        - python 3.8.5 h26836e1_1
        - readline 8.0 h1de35cc_0
        - ruamel_yaml 0.15.87 py38haf1e3a3_1
        - setuptools 50.3.0 py38h0dc7051_1
        - six 1.15.0 py_0
        - sqlite 3.33.0 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - tqdm 4.50.2 py_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h1de35cc_0
        - yaml 0.2.5 haf1e3a3_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - conda-package-handling >=1.3.0
        - pycosat >=0.6.3
        - pyopenssl >=16.2.0
        - python >=3.8,<3.9.0a0
        - requests >=2.18.4,<3
        - ruamel_yaml >=0.11.14,<0.16
        - setuptools >=31.0.1
    run_constrained:
        - conda-build >=3
        - conda-env >=2.6
        - cytoolz >=0.8.1
test:
    downstreams:
        - conda-smithy
    files:
        - test_conda.sh
    imports:
        - conda
        - conda_env
    requires:
        - mock
        - pexpect
        - pytest
        - responses
    source_files:
        - conftest.py
        - setup.cfg
        - tests
about:
    description: 'Conda is an open source package management system and environment
        management system for installing multiple versions of software packages and
        their dependencies and switching easily between them. It works on Linux, OS
        X and Windows, and was created for Python programs but can package and distribute
        any software.

        '
    dev_url: https://github.com/conda/conda
    doc_url: https://conda.io/projects/conda/en/latest/
    home: https://conda.io
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: OS-agnostic, system-level binary package and environment manager.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chenghlee
        - jakirkham
        - jjhelmus
        - kalefranz
        - mbargull
        - mcg1969
        - mingwandroid
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
