# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/6c2690e2-701d-495a-7c1e-39040170fef7/volume/rsync-recipes/pip-20.2.4-python_3.8-on-osx, last modified Tue Nov  3 11:41:57 2020
# ------------------------------------------------

package:
    name: pip
    version: 20.2.4
source:
    patches:
        - 0001-Win32-Fix-Py_DEBUG-determination-in-_derive_abi-in-w.patch
    sha256: 85c99a857ea0fb0aedf23833d9be5c40cf253fe24443f0829c7b472e23c364a1
    url: https://pypi.io/packages/source/p/pip/pip-20.2.4.tar.gz
build:
    disable_pip: true
    entry_points:
        - pip = pip._internal.cli.main:main
        - pip3 = pip._internal.cli.main:main
    number: '0'
    string: py38hecd8cb5_0
requirements:
    host:
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 pyhd3eb1b0_3
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 h1de35cc_1
        - libffi 3.3 hb1e8313_2
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1h haf1e3a3_0
        - python 3.8.5 h26836e1_1
        - readline 8.0 h1de35cc_0
        - setuptools 50.3.0 py38hecd8cb5_1
        - sqlite 3.33.0 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
        - setuptools
        - wheel
test:
    commands:
        - pip -h
        - pip list
    imports:
        - pip
about:
    dev_url: https://github.com/pypa/pip
    doc_url: https://pip.pypa.io/en/stable/
    home: https://pip.pypa.io/en/stable/
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: PyPA recommended tool for installing Python packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
