# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/3e3d5813-e4fa-40da-6aa3-5a29558f718e/volume/combined_recipe, last modified Thu Oct 15 14:04:37 2020
# ------------------------------------------------

package:
    name: pillow
    version: 8.0.0
source:
    sha256: 59304c67d12394815331eda95ec892bf54ad95e0aa7bc1ccd8e0a4a5a25d4bf3
    url: https://pypi.io/packages/source/P/Pillow/Pillow-8.0.0.tar.gz
build:
    ignore_run_exports:
        - jpeg
        - tk
    number: '0'
    string: py38h1a82f1a_0
requirements:
    build:
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libllvm10 10.0.0 h21ff451_2
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_2
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 py38_0
        - freetype 2.10.3 ha233b18_0
        - jpeg 9b he5867d9_2
        - lcms2 2.11 h92f6f08_0
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 h1de35cc_1
        - libffi 3.3 hb1e8313_2
        - libpng 1.6.37 ha441bb4_0
        - libtiff 4.1.0 hcb84e12_1
        - lz4-c 1.9.2 h79c402e_3
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1h haf1e3a3_0
        - pip 20.2.3 py38_0
        - python 3.8.5 h26836e1_1
        - readline 8.0 h1de35cc_0
        - setuptools 50.3.0 py38h0dc7051_1
        - sqlite 3.33.0 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
        - zstd 1.4.5 h41d2c2f_0
    run:
        - freetype >=2.10.3,<3.0a0
        - jpeg
        - lcms2 >=2.11,<3.0a0
        - libtiff >=4.1.0,<5.0a0
        - olefile
        - python >=3.8,<3.9.0a0
        - tk
        - zlib >=1.2.11,<1.3.0a0
test:
    imports:
        - PIL
        - PIL.Image
        - PIL.ImageCms
        - PIL._imaging
        - PIL._imagingft
        - PIL._imagingmath
        - PIL._imagingmorph
about:
    description: 'Pillow is the friendly PIL fork. PIL is the Python Imaging Library,

        adds image processing capabilities to your Python interpreter.

        '
    dev_url: https://github.com/python-pillow/Pillow
    doc_source_url: https://github.com/python-pillow/Pillow/blob/4.2.x/docs/index.rst
    doc_url: http://pillow.readthedocs.io/en/4.2.x/
    home: https://pillow.readthedocs.io
    license: LicenseRef-PIL
    license_file: LICENSE
    summary: Pillow is the friendly PIL fork by Alex Clark and Contributors
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - ocefpaf
        - patricksnape
        - pelson
