# This file created by conda-build 3.20.4
# ------------------------------------------------

package:
    name: numpy-base
    version: 1.19.2
source:
    patches:
        - 0001-Obtain-and-prefer-custom-gfortran-from-env-variable.patch
        - 0002-intel_mkl-version.patch
        - 0003-intel_init_mkl.patch
    sha256: 74d0cf50aa28af81874aca3e67560945afd783b2a006913577d6cddc35a824a6
    url: https://github.com/numpy/numpy/releases/download/v1.19.2/numpy-1.19.2.tar.gz
build:
    number: 0
    string: py38hcfb5961_0
requirements:
    build:
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libllvm10 10.0.0 h21ff451_0
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_0
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 py38_0
        - cython 0.29.21 py38hb1e8313_0
        - intel-openmp 2019.4 233
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 h1de35cc_1
        - libffi 3.3 hb1e8313_2
        - mkl 2019.4 233
        - mkl-devel 2019.4 233
        - mkl-include 2019.4 233
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1h haf1e3a3_0
        - pip 20.2.4 py38_0
        - python 3.8.5 h26836e1_1
        - readline 8.0 h1de35cc_0
        - setuptools 50.3.0 py38h0dc7051_1
        - sqlite 3.33.0 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - blas 1.0 mkl
        - mkl >=2019.4,<2020.0a0
        - mkl-service >=2,<3.0a0
        - python >=3.8,<3.9.0a0
test:
    commands:
        - test -e $SP_DIR/numpy/distutils/site.cfg
about:
    description: 'NumPy is the fundamental package needed for scientific computing
        with Python.

        '
    dev_source_url: https://github.com/numpy/numpy/tree/master/doc
    dev_url: https://github.com/numpy/numpy
    doc_url: https://docs.scipy.org/doc/numpy/reference/
    home: http://numpy.scipy.org/
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Array processing for numbers, strings, records, and objects.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chenghlee
        - jakirkham
        - msarahan
        - ocefpaf
        - pelson
        - rgommers
